customhost = "employee.cil4uwyoii6v.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "ayeshanadirabintiirwan-bucket"
customregion = "us-east-1"
